src/Controller/Entity/Funcionario.php
<?php 
namespace App\Entity;

class Funcionario {
    private $nome; 
    private $dataDeNascimento;
    private $dataDeEntrada;

    public function getNome(){
        return $nome;
    }

    public function setNome($nome) {
        $this->nome = $nome;
    }

    public function getDataDeNascimento(){
        return $dataDeNascimento;
    }

    public function setDataDeNascimento($dataDeNascimento){
        $this->dataDeNascimento = $dataDeNascimento;
    }

    public function getDataDeEntrada() {
        return $dataDeEntrada;
    }

    public function setDataDeEntrada($dataDeEntrada) {
        $this->dataDeEntrada = $dataDeEntrada;
    }

    public function getTempoNaEmpresa() {
        $hoje = new \DateTime();
        $diferenca = $hoje->diff($this->dataDeEntrada);
        
        return $diferenca;
    }
}

?>

src/Entity/Funcionario.php
<?php 
namespace App\Entity;

class Funcionario {
    private $nome; 
    private $dataDeNascimento;
    private $dataDeEntrada;

    public function getNome(){
        return $this->nome;
    }

    public function setNome($nome) {
        $this->nome = $nome;
    }

    public function getDataDeNascimento(){
        return $this->dataDeNascimento;
    }

    public function setDataDeNascimento($dataDeNascimento){
        $this->dataDeNascimento = $dataDeNascimento;
    }

    public function getDataDeEntrada() {
        return $this->dataDeEntrada;
    }

    public function setDataDeEntrada($dataDeEntrada) {
        $this->dataDeEntrada = $dataDeEntrada;
    }

    public function getTempoNaEmpresa() {
        $hoje = new \DateTime();
        $diferenca = $hoje->diff($this->dataDeEntrada);
        
        return $diferenca;
    }
}

?>

src/Controller/FuncionarioController.php
<?php
namespace App\Controller;

use App\Entity\Funcionario;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class FuncionarioController extends AbstractController {
    
    /**
     * @Route("/funcionario/mostra/{nome}")
     */
    public function mostraAction($nome = 'Guilherme') {
        $funcionario = new Funcionario();

        $funcionario->setNome($nome);
        $funcionario->setDataDeNascimento(new \DateTime("26-01-1994"));
        $funcionario->setDataDeEntrada(new \DateTime("21-03-2012"));

        return $this->render('Funcionario/mostra.html.twig',['funcionario' => $funcionario]);
    }
}

?>

src/Controller/HomController.php
<?php
    namespace App\Controller;

    use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
    use Symfony\Component\Routing\Annotation\Route;
    
    class HomeController extends AbstractController {
        /**
         * @Route("/")
         */
        public function indexAction() {
            return $this->render('index.html.twig');        
        }
    }
?>

src/Controller/HomeController.php
<?php
    namespace App\Controller;

    use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
    use Symfony\Component\Routing\Annotation\Route;
    
    class HomeController extends AbstractController {
        /**
         * @Route("/")
         */
        public function indexAction() {
            return $this->render('index.html.twig');        
        }
    }
?>

templates/Funcionario/mostra.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>TikTok</title>
    </head>
    <body>
        dados do funcionario
        <table>
            <tr>
                <th>nome</th>
                <td>{{ funcionario.nome }}</td>
            </tr>
            <tr>
                <th>data de nascimento</th>
                <td>{{ funcionario.dataDeNascimento|date("d-m-Y") }}</td>
            </tr>
            <tr>
                <th>data de entrada</th>
                <td>{{ funcionario.dataDeEntrada|date("d-m-Y") }}</td>
            </tr>
            <tr>
                <th>tempo na empresa</th>
                <td>{{ funcionario.tempoNaEmpresa|date("%Y anos, %m meses, %d dias") }}</td>
            </tr>
        </table>
    </body>
</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/index.html.twig
<html> 
    <meta charset="UTF-8">
    <title> TikTok </title> 
    <head> 
    </head> 
    <body>
        Bem vindo!
        {{ 'now' | date('d/m/Y h:i') }}
    </body> 

</html>